use_frameworks!

platform :ios, '10.0'

target 'MYCategoryKit_Example' do
  pod 'MYCategoryKit', :path => '../'

  target 'MYCategoryKit_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
